"""
core/vin/brand_models.py
=========================
Brand → model catalogue scraped from the OPSI vehicle registration database
(Slovenia, 1.58 M registrations, 1990–2020).

Used by core/vin/__init__.py to populate EngineDNA.common_models and to
enrich partial-confidence lookups with a list of plausible model names.

Source: OPSI_podatki_reg._vozilih_30.06.2023 (Nio_vozila_1-3.csv)
Filtered: M1/N1 category, first registration 1990-2020, min 3 registrations.
Total brands: 49  |  Total unique brand-model pairs: 2416
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Brand → [model, ...] mapping
# Keys are uppercase canonical brand names as they appear in the OPSI dataset.
# ---------------------------------------------------------------------------

BRAND_MODELS: dict[str, list[str]] = {
    'ALFA ROMEO': [
        '4C',
        'ALFA',
        'ALFA 75',
        'ALFA ROMEO',
        'BRERA',
        'GIULIA',
        'GIULIETTA',
        'GT',
        'GTV',
        'MITO',
        'SPIDER',
        'STELVIO',
    ],
    'AUDI': [
        'A 2',
        'A 3',
        'A 3  1.6',
        'A 3  1.8',
        'A 4',
        'A 4  1.6',
        'A 4  1.8',
        'A 4  1.9',
        'A 4  1.9 TDI',
        'A 4  AVANT 1.9',
        'A 6',
        'A 6  1.9',
        'A 8',
        'A1',
        'A2',
        'A3',
        'A3 1.9 TDI',
        'A3 40 E-TRON',
        'A4',
        'A4 1.9 TDI',
        'A4 ALLROAD',
        'A4 ALLROAD QUATRO',
        'A4 ALLROAD QUATTRO',
        'A4 AVANT',
        'A4 AVANT 1.9 TDI',
        'A4 AVANT 2.0',
        'A5',
        'A5 CABRIOLET',
        'A6',
        'A6 55 E',
        'A6 ALLROAD',
        'A6 ALLROAD QUATTRO',
        'A7',
        'A8',
        'A8 L',
        'ALLROAD',
        'AUDI',
        'AUDI A 4 1.9 TDI',
        'AUDI A4 1,9 TDI',
        'AUDI A6 1,9 TDI',
        'AUDI AUDI A3 1.6 74KW',
        'AUDI AUDI A4 1,6L 74KW',
        'AUDI AUDI A4 1,8L 20V 92KW',
        'CABRIOLET',
        'COUPE',
        'E-TRON',
        'E-TRON 50',
        'E-TRON 55',
        'E-TRON SPORTBACK 50',
        'E-TRON SPORTBACK 55',
        'Q2',
        'Q3',
        'Q5',
        'Q5 55 E',
        'Q7',
        'Q7 E-TRON',
        'Q8',
        'R8',
        'RS 3',
        'RS 3 SPORTBACK',
        'RS 4',
        'RS 6',
        'RS Q3',
        'RS Q8',
        'RS3',
        'RS4',
        'RS4 AVANT',
        'RS5',
        'RS6',
        'RS7',
        'S 8',
        'S1',
        'S3',
        'S4',
        'S4 AVANT',
        'S5',
        'S6',
        'S7',
        'S8',
        'S8 PLUS',
        'SQ5',
        'SQ7',
        'SQ8',
        'TT',
        'TT COUPE',
        'TT ROADSTER',
        'TT RS',
        'TTS',
    ],
    'BENTLEY': [
        'CONTINENTAL',
        'CONTINENTAL GT',
    ],
    'BMW': [
        '316 I',
        '316I',
        '318  I',
        '318 I',
        '318I',
        '320 D',
        '320 I',
        '320I',
        '323I',
        '328 CI',
        '520 I',
        '523  I',
        '530 X',
        '850 I',
        'BMW',
        'BMW 3',
        'BMW 316 I',
        'BMW 316I',
        'BMW 316I COMPACT',
        'BMW 318',
        'BMW 318 I',
        'BMW 318I',
        'BMW 320',
        'BMW 320 D',
        'BMW 320D',
        'BMW 320I',
        'BMW 323 CI',
        'BMW 520I',
        'BMW 523 I',
        'BMW 523I',
        'BMW 525 D',
        'BMW 528I',
        'BMW 530 D',
        'BMW 530D',
        'BMW SERIJA 3 ( E36 )',
        'BMW SERIJA 5 ( E39 )',
        'I3',
        'M',
        'M 3',
        'M 5',
        'M 6',
        'M COUPE',
        'M135',
        'M140',
        'M2',
        'M2 COMPETITION',
        'M235',
        'M240',
        'M3',
        'M340',
        'M4',
        'M4 CS',
        'M440',
        'M5',
        'M5 COMPETITION',
        'M550',
        'M6',
        'M8 COMPETITION',
        'M850',
        'X 3',
        'X 5',
        'X1',
        'X2',
        'X3',
        'X3 M COMPETITION',
        'X4',
        'X4 M COMPETITION',
        'X5',
        'X5 M',
        'X6',
        'X6 M',
        'X6 M COMPETITION',
        'X7',
        'Z',
        'Z 3',
        'Z 4',
        'Z3',
        'Z4',
        'Z4 2.2L',
        'Z4 M',
    ],
    'CHEVROLET': [
        'AVEO',
        'CAMARO',
        'CAMARO CONVERTIBLE',
        'CAMARO COUPE',
        'CAMARO SS',
        'CAPTIVA',
        'CHEVROLET',
        'CORVETTE',
        'CORVETTE C4',
        'CRUZE',
        'EPICA',
        'EVANDA',
        'KALOS',
        'LACETTI',
        'LUMINA',
        'MALIBU',
        'MATIZ',
        'NUBIRA',
        'ORLANDO',
        'SILVERADO',
        'SPARK',
        'SUBURBAN',
        'TACUMA',
        'TAHOE',
        'TRAX',
        'VOLT',
    ],
    'CHRYSLER': [
        '300 C',
        '300C',
        '300M',
        'CHRYSLER',
        'CROSSFIRE',
        'GRAND',
        'GRAND VOYAGER',
        'LE BARON',
        'NEON',
        'PT',
        'PT CRUISER',
        'SEBRING',
        'STRATUS',
        'TOWN AND COUNTRY',
        'VOYAGER',
    ],
    'CITROEN': [
        '2 CV',
        'AX',
        'AX  AUDACE 1.0 I',
        'BERLINGO',
        'BERLINGO 1.1',
        'BERLINGO 1.4',
        'BERLINGO 1.6',
        'BERLINGO 1.8 D',
        'BERLINGO 1.9',
        'BERLINGO 1.9 D',
        'BERLINGO 2.0',
        'BERLINGO 2.0 HDI',
        'BERLINGO 2.0 HDI MUL',
        'BERLINGO BREAK 1.4',
        'BERLINGO BREAK 1.6',
        'BERLINGO BREAK 2.0',
        'BERLINGO FURGON 1.1',
        'BERLINGO FURGON 1.4',
        'BERLINGO FURGON 1.9',
        'BERLINGO FURGON 2.0',
        'BX',
        'C',
        'C 1',
        'C 15',
        'C 15 D',
        'C 15 FURGON 1.8',
        'C 15 FURGON 1.9',
        'C 2',
        'C 25',
        'C 25 D',
        'C 25 E',
        'C 3',
        'C 3  1.1',
        'C 3  1.4',
        'C 3 PLURIEL',
        'C 4',
        'C 5',
        'C 5 II',
        'C 8',
        'C 8 2.2',
        'C ZERO',
        'C-CROSSER',
        'C-ELYSEE',
        'C1',
        'C2',
        'C25',
        'C3',
        'C3  1.4',
        'C3 1.4',
        'C3 AIRCROSS',
        'C3 PICASSO',
        'C3 PLURIEL',
        'C4',
        'C4 1.6',
        'C4 AIRCROSS 2X4',
        'C4 AIRCROSS 4X2',
        'C4 AIRCROSS 4X4',
        'C4 CACTUS',
        'C4 PICASSO',
        'C4 SPACETOURER',
        'C5',
        'C5 AIRCROSS',
        'C5 II',
        'C5 III',
        'C5II',
        'C6',
        'C8',
        'CITROEN',
        'CITROEN AX AUDACE 1.OI 3P',
        'CITROEN AX SPOT 1.0I 3P',
        'CITROEN JUMPER 2,5 TDI',
        'CITROEN JUMPER 35 L 2,2 HDI',
        'CITROEN JUMPER 35 L 2,5 D',
        'CITROEN JUMPER 35 L 2,8 HDI',
        'CITROEN SAXO X 1.0I 3P',
        'CITROEN XSARA X 1.4I 5P',
        'CITROËN',
        'DS3',
        'DS3 RACING',
        'DS4',
        'DS5',
        'DYANE',
        'EVASION',
        'JUMPER',
        'JUMPER 2.0',
        'JUMPER 2.2',
        'JUMPER 2.5',
        'JUMPER 2.5 D',
        'JUMPER 2.5 TD',
        'JUMPER 2.5 TDI',
        'JUMPER 2.8',
        'JUMPER 27C 1.9',
        'JUMPER 29 C 2.0',
        'JUMPER 29C 2.0',
        'JUMPER 3.0',
        'JUMPER 31M 2.5',
        'JUMPER 31M 2.5D',
        'JUMPER 31MH 2.5',
        'JUMPER 33 M 2.8',
        'JUMPER 33 MH 2.8',
        'JUMPER 33M 2.0',
        'JUMPER 33M 2.8',
        'JUMPER 33MH 2.8',
        'JUMPER 35 L 2.2 HDI',
        'JUMPER 35 L 2.5',
        'JUMPER 35 L 2.5 TDI',
        'JUMPER 35 L 2.8',
        'JUMPER 35 L 2.8 HDI',
        'JUMPER 35 LH 2.2',
        'JUMPER 35 LH 2.5',
        'JUMPER 35 LH 2.5 D',
        'JUMPER 35 LH 2.5 TDI',
        'JUMPER 35 LH 2.8',
        'JUMPER 35 LH TD',
        'JUMPER 35 MH 2.2',
        'JUMPER 35 MH 2.5 D',
        'JUMPER 35 MH 2.8',
        'JUMPER 35L 2.2',
        'JUMPER 35LH 2.2',
        'JUMPER 35LH 2.8',
        'JUMPER 35MH 2.2',
        'JUMPER 35MH 2.5',
        'JUMPER 35MH 2.8',
        'JUMPER ODER RELAY',
        'JUMPY',
        'JUMPY 1.5',
        'JUMPY 1.6',
        'JUMPY 1.9',
        'JUMPY 2.0',
        'JUMPY FURGON',
        'JUMPY FURGON 1.9',
        'JUMPY FURGON 2.0',
        'JUMPY SPACE TOURER',
        'MEHARI',
        'NEMO',
        'NEMO 1.3',
        'NEMO 1.4',
        'NEMO FG 1.4',
        'SAXO',
        'SAXO  1.0',
        'SAXO  1.0 I',
        'SAXO  1.1',
        'SAXO  1.1 I',
        'SAXO FURGON 1.1',
        'XANTIA',
        'XM',
        'XSARA',
        'XSARA  1.4',
        'XSARA  1.6',
        'XSARA  1.6 I',
        'XSARA  2.0  HDI',
        'XSARA  BREAK 1.6',
        'XSARA  BREAK 2.0',
        'XSARA  PICASSO',
        'XSARA PICASSO',
        'XSARA PICASSO 2.0 HDI',
        'ZX',
    ],
    'DACIA': [
        'DOKKER',
        'DOKKER 1.5',
        'DOKKER 1.6',
        'DUSTER',
        'DUSTER 1.5',
        'LODGY',
        'LOGAN',
        'LOGAN FURGON 1.5',
        'LOGAN FURGON 1.6',
        'LOGAN MCV',
        'LOGAN PICK UP 1.5',
        'LOGAN PICK UP 1.6',
        'SANDERO',
        'SANDERO 1.2',
        'SANDERO 1.5',
    ],
    'DAEWOO': [
        'DAEWOO',
        'DAEWOO KALOS',
        'ESPERO',
        'EVANDA',
        'KALOS',
        'KORANDO',
        'LANOS',
        'LANOS  1.5',
        'LANOS 1.5',
        'LEGANZA',
        'MATIZ',
        'MUSSO',
        'NEXIA',
        'NUBIRA',
        'NUBIRA  1.6',
        'RACER',
        'TACUMA',
        'TICO',
    ],
    'DODGE': [
        'AVENGER',
        'CALIBER',
        'CARAVAN',
        'CHALLENGER',
        'DODGE RAM 1500',
        'GRAND CARAVAN',
        'JEEP DODGE',
        'JOURNEY',
        'NITRO',
        'RAM 1500',
        'RAM 1500 4X4',
        'RAM 2500',
        'RAM1500',
        'RAM1500 4X4',
        'STEALTH',
    ],
    'DS': [
        'DS3',
        'DS3 CROSSBACK',
        'DS4',
        'DS5',
        'DS7',
    ],
    'FERRARI': [
        '488 GTB',
        'CALIFORNIA',
        'F12',
    ],
    'FIAT': [
        '1100 E',
        '1107 A',
        '124 SPIDER',
        '126 P',
        '500 ABARTH',
        '500 E',
        '500E',
        '500L',
        '500L 1.6',
        '500L VAN 1.3',
        '500X',
        'ABARTH 500',
        'ALBEA',
        'AR',
        'BARCHETA',
        'BARCHETTA',
        'BRAVA',
        'BRAVO',
        'CAMPAGNOLA',
        'CINQUECENTO',
        'COUPE',
        'CROMA',
        'DOBLO',
        'DOBLO 1.6',
        'DOBLO 1.9',
        'DOBLO CARGO',
        'DOBLO CARGO 1.2',
        'DOBLO CARGO 1.3',
        'DOBLO CARGO 1.4',
        'DOBLO CARGO 1.6',
        'DOBLO CARGO 1.9',
        'DOBLO CARGO 2.0',
        'DUCATO',
        'DUCATO  2.3',
        'DUCATO  2.8',
        'DUCATO 1.9',
        'DUCATO 1.9 TD',
        'DUCATO 10Q 1.9',
        'DUCATO 10Q 2.8',
        'DUCATO 10Q VAN 1.9',
        'DUCATO 11Q 2.0',
        'DUCATO 14 Q 2.8',
        'DUCATO 14Q 1.9',
        'DUCATO 14Q 2.5',
        'DUCATO 14Q 2.8',
        'DUCATO 15Q 2,8',
        'DUCATO 15Q 2.0',
        'DUCATO 15Q 2.3',
        'DUCATO 15Q 2.8',
        'DUCATO 18 Q',
        'DUCATO 18 Q 2.8',
        'DUCATO 18 VAN MAXI 2.5',
        'DUCATO 18Q',
        'DUCATO 18Q 2.3',
        'DUCATO 18Q 2.8',
        'DUCATO 18Q VAN 2.8',
        'DUCATO 2,3',
        'DUCATO 2.0',
        'DUCATO 2.2',
        'DUCATO 2.3',
        'DUCATO 2.5',
        'DUCATO 2.5 D',
        'DUCATO 2.5 DS',
        'DUCATO 2.5 TDI',
        'DUCATO 2.8',
        'DUCATO 2.8 JTD',
        'DUCATO 2500 D',
        'DUCATO 3.0',
        'DUCATO MAXI 2.5 DS',
        'DUCATO MAXI 2.5 TDI',
        'DUCATO MAXI 2.5 TDS',
        'DUCATO SHARKY',
        'DUCATO VAN 2.2',
        'ELNAGH',
        'FIAT',
        'FIAT 500',
        'FIAT DUCATO',
        'FIAT DUCATO 1,9 TD',
        'FIAT DUCATO 18 Q 2,8 JTD',
        'FIAT DUCATO 18 Q 2,8 TD',
        'FIAT DUCATO 18Q 2,8 TD',
        'FIAT DUCATO 2,8 JTD',
        'FIAT DUCATO 2,8 TD',
        'FIAT PANDA',
        'FIAT PANDA VAN',
        'FIAT PUNTO',
        'FIAT SCUDO',
        'FIAT STILO 1,9 JTD',
        'FIAT UNO',
        'FIORINO',
        'FIORINO 1.3',
        'FIORINO 1.4',
        'FIORINO 1.7 D',
        'FIORINO 1.7 DS',
        'FIORINO VAN 1.4',
        'FIORINO VAN 1.7',
        'FREEMONT',
        'FULLBACK',
        'GRANDE PUNTO',
        'GRANDE PUNTO 1.3',
        'GRANDE PUNTO VAN 1.3',
        'GRANDE PUNTO VAN 1.4',
        'GRANDUCA',
        'HYMER',
        'IDEA',
        'LAGAN',
        'LINEA',
        'MAREA',
        'MARENGO',
        'MULTIPLA',
        'PALIO',
        'PANDA',
        'PANDA  1.1',
        'PANDA  1.3',
        'PANDA 1.1',
        'PANDA 1.2',
        'PANDA 1.3',
        'PANDA 4X4',
        'PANDA TREKKING',
        'PANDA VAN',
        'PUNTO',
        'PUNTO  1.2',
        'PUNTO  55 S',
        'PUNTO 1.2',
        'PUNTO 1.3',
        'PUNTO EVO',
        'PUNTO EVO VAN 1.3',
        'PUNTO GRANDE',
        'PUNTO VAN',
        'PUNTO VAN 1.2',
        'PUNTO VAN 1.3',
        'PUNTO VAN 1.4',
        'PUNTO VAN 1.9',
        'QUBO',
        'SCUDO',
        'SCUDO 1.6',
        'SCUDO 1.9 D',
        'SCUDO 1.9 TD',
        'SCUDO 2.0',
        'SCUDO VAN 1.9',
        'SCUDO VAN 2.0',
        'SCUDO VAN 2.0 JTD',
        'SEDICI',
        'SEICENTO',
        'SEICENTO  1100',
        'SEICENTO VAN 1100',
        'SHARKY',
        'STILO',
        'TALENTO',
        'TEMPRA',
        'TIPO',
        'TIPO  1.4 IES',
        'ULYSSE',
        'UNO',
        'YPSILON',
    ],
    'FORD': [
        'A',
        'B-MAX',
        'C-MAX',
        'CMAX',
        'COUGAR',
        'ECOSPORT',
        'EDGE',
        'ESCORT',
        'EXPLORER',
        'F-150',
        'F0RD',
        'F150',
        'FIESTA',
        'FIESTA  1.3',
        'FIESTA 1.5',
        'FIESTA VAN 1.25',
        'FIESTA VAN 1.4',
        'FIESTA VAN 1.5',
        'FLASH',
        'FOCUS',
        'FOCUS  1.4',
        'FOCUS  1.6',
        'FOCUS  WAGON 1.6',
        'FOCUS 1.0',
        'FOCUS 1.4',
        'FOCUS 1.5',
        'FOCUS 1.5 D',
        'FOCUS 2.0',
        'FOCUS 2.3',
        'FOCUS C-MAX',
        'FOCUS RS',
        'FOCUS ST',
        'FORD',
        'FORD MONDEO 1,8 TDI',
        'FORD MUSTANG',
        'FUSION',
        'G TOURNEO CONNECT 1.5 74 230 L2 LWB 110V B6+D6',
        'G TOURNEO CONNECT 1.5 88 230 L2 LWB 120V A8',
        'G TOURNEO CONNECT 1.5 88 230 L2 LWB 120V B6+D6',
        'G TOURNEO CONNECT 230 L2',
        'GALAXY',
        'GALAXY 1.5',
        'GALAXY 2.0',
        'GENESIS',
        'GENESIS 31 M08',
        'GRAND C-MAX',
        'JEEP',
        'JEEP GPW',
        'KA',
        'KA+',
        'KUGA',
        'MAVERICK',
        'MONDEO',
        'MONDEO  2.0',
        'MONDEO 1.5',
        'MONDEO 2.0',
        'MONDEO 2.0 ECOBLUE',
        'MONDEO HIBRID',
        'MUSTANG',
        'MUSTANG ECOBOOST',
        'MUSTANG GT',
        'ORION',
        'PROBE',
        'PUMA',
        'RANGER',
        'RANGER  2.5',
        'RANGER 2.0',
        'RANGER 2.2',
        'RANGER 2.5',
        'RANGER 3.0',
        'RANGER 3.2',
        'RANGER RAPTOR 2.0',
        'RIMOR',
        'S-MAX',
        'S-MAX 1.5',
        'S-MAX 2.0',
        'S-MAX 2.0 ECOBLUE 110 A8',
        'S-MAX 2.0 ECOBLUE 140 A8',
        'S-MAX 2.0 ECOBLUE 140 A8 AWD',
        'SCORPIO',
        'SIERRA',
        'SMAX',
        'STREET KA',
        "TOU. CUSTOM 17'",
        "TOU. CUSTOM 17''",
        'TOURNEO',
        'TOURNEO CONNECT',
        'TOURNEO CONNECT 1.5 74 205 L1 SWB 110V B6+D6',
        'TOURNEO CONNECT 1.5 88 205 L1 SWB 120V B6+D6',
        'TOURNEO CONNECT 200 S',
        'TOURNEO CONNECT 205 L1',
        'TOURNEO CONNECT 210 S',
        'TOURNEO CONNECT 220 S',
        'TOURNEO CONNECT 230 L',
        'TOURNEO CONNECT 230 L2',
        'TOURNEO COURIER',
        'TOURNEO CUSTOM',
        'TOURNEO CUSTOM BC',
        "TOURNOE CUSTOM 17'",
        'TRA. CUSTOM KOMBI',
        'TRANSIT',
        'TRANSIT 100',
        'TRANSIT 100 L',
        'TRANSIT 100 L 2.5',
        'TRANSIT 100 SWB',
        'TRANSIT 150',
        'TRANSIT 150 M 2.4',
        'TRANSIT 150 TD',
        'TRANSIT 190',
        'TRANSIT 190 2.5 D',
        'TRANSIT 190 EF',
        'TRANSIT 2.0',
        'TRANSIT 2.2',
        'TRANSIT 2.4',
        'TRANSIT 2.5 D',
        'TRANSIT 280 S 2.0',
        'TRANSIT 280 S 2.2',
        'TRANSIT 300 L 2.0',
        'TRANSIT 300 L 2.2',
        'TRANSIT 300 M 2.0',
        'TRANSIT 300 M 2.2',
        'TRANSIT 300 S',
        'TRANSIT 300 S 2.0',
        'TRANSIT 300 S 2.2',
        'TRANSIT 300M',
        'TRANSIT 300M 2.0',
        'TRANSIT 300M 2.2',
        'TRANSIT 330 L 2.0',
        'TRANSIT 330 L 2.2',
        'TRANSIT 330 M 2.0',
        'TRANSIT 330 M 2.2',
        'TRANSIT 330 M 2.4',
        'TRANSIT 330 S 2.2',
        'TRANSIT 350 EF 2.4',
        'TRANSIT 350 L',
        'TRANSIT 350 L 2.0',
        'TRANSIT 350 L 2.2',
        'TRANSIT 350 L 2.4',
        'TRANSIT 350 L 3.2',
        'TRANSIT 350 L EF 2.4',
        'TRANSIT 350 L EF 3.2',
        'TRANSIT 350 M 2.2',
        'TRANSIT 350 M 2.4',
        'TRANSIT 350L',
        'TRANSIT 350L 2.2',
        'TRANSIT 350L 2.4',
        'TRANSIT 350M 2.2',
        'TRANSIT CONNECT',
        'TRANSIT CONNECT 1.5 74 200 L1 110V SWB B6+D6',
        'TRANSIT CONNECT 1.5 74 220 L1 310V SWB CK B6+D6',
        'TRANSIT CONNECT 1.5 74 230 L2 310V LWB CK B6+D6',
        'TRANSIT CONNECT 1.5 88 200 L1 110V SWB B6+D6',
        'TRANSIT CONNECT 1.5 88 210 L2 110V LWB B6+D6',
        'TRANSIT CONNECT 1.5 88 220 L1 310V SWB CK B6+D6',
        'TRANSIT CONNECT 1.5 88 230 L2 310V LWB CK B6+D6',
        'TRANSIT CONNECT 1.8',
        'TRANSIT CONNECT 200',
        'TRANSIT CONNECT 200 L1',
        'TRANSIT CONNECT 200 S 1.8',
        'TRANSIT CONNECT 210 L2',
        'TRANSIT CONNECT 220',
        'TRANSIT CONNECT 220 L 1.8',
        'TRANSIT CONNECT 220 L1',
        'TRANSIT CONNECT 220 S 1.8',
        'TRANSIT CONNECT 230 L 1.8',
        'TRANSIT CONNECT 230 L2',
        'TRANSIT CONNECT 240 L2',
        'TRANSIT CONNECT LWB CK',
        'TRANSIT COURIER',
        'TRANSIT CUSTOM',
        'TRANSIT CUSTOM DCIV',
        'TRANSIT CUSTOM KOMBI',
        'TRANSIT CUSTOM VAN',
        'TRANSIT DCIV',
        'TRANSIT KOMBI',
        'TRANSIT KOMBI 2.0 EB 125 350 L3H2 HEA',
        'TRANSIT VAN',
        'WILLYS',
    ],
    'HONDA': [
        'ACCORD',
        'ACCORD TOURER',
        'CIVIC',
        'CIVIC CRX',
        'CONCERTO',
        'CR-V',
        'CR-Z',
        'CRV',
        'CRV 2.0 I',
        'CRX',
        'FR-V',
        'FRV',
        'HONDA',
        'HONDA ACCORD 1.8I ES',
        'HONDA ACCORD 1.8I LS',
        'HONDA CIVIC',
        'HONDA CIVIC 1.4 I',
        'HONDA CIVIC 1.4 IS',
        'HONDA CIVIC 1.4 LS',
        'HONDA CIVIC 1.6I ES',
        'HONDA CIVIC 1.6I LS',
        'HONDA CR-V 2.0 I',
        'HONDA E',
        'HONDA HR-V 1.6',
        'HONDA HR-V 1.6I 4WD',
        'HONDA HR-V 1.6I CVT 4WD',
        'HONDA HR-V HR-V',
        'HONDA JAZZ 1.4 LS',
        'HR-V',
        'HR-V 1.6',
        'HRV',
        'INSIGHT',
        'INTEGRA',
        'JAZZ',
        'LEGEND',
        'LOGO',
        'PRELUDE',
        'S',
        'S 2000',
        'S2000',
        'SHUTTLE',
        'STREAM',
    ],
    'HYUNDAI': [
        'ACCENT',
        'ACCENT  1.3 LS',
        'ACCENT  1.5',
        'ATOS',
        'ATOS-PRIME',
        'ATOS-PRIME  1.0',
        'COUPE',
        'ELANTRA',
        'GALLOPER',
        'GALLOPER 2.5',
        'GALOPER',
        'GETZ',
        'GRAND SANTA FE',
        'H 100',
        'H 100 DIESEL',
        'H 100 DLX',
        'H 100 SUPER CAB',
        'H 100 TRUCK',
        'H 100 TRUCK 2.5 GLX',
        'H 100 WINDOW VAN',
        'H-1',
        'H-1 2.5',
        'H-1 VAN 2.4',
        'H-1 VAN 2.5',
        'H-100',
        'H-100 AU TRUCK',
        'H350',
        'HYUNDAI',
        'HYUNDAI ACCENT 1,3',
        'HYUNDAI ACCENT 1,5',
        'HYUNDAI ACCENT 1.3 LS',
        'HYUNDAI ACCENT 1.5 GLS',
        'HYUNDAI ATOS - PRIME 1,0',
        'HYUNDAI ATOS 1,0 GLS',
        'HYUNDAI COUPE 1,6',
        'HYUNDAI ELANTRA 1,6',
        'HYUNDAI ELANTRA 2,0',
        'HYUNDAI GALLOPER 2,5 TDI',
        'HYUNDAI GALLOPER LWB 2,5 XL T',
        'HYUNDAI H-100 TRUCK 2,5',
        'I 10',
        'I 20',
        'I 30',
        'I 30 CW',
        'I10',
        'I20',
        'I30',
        'I30 CW',
        'I30 CW NS',
        'I30 FB',
        'I30 FB NS',
        'I30 NS',
        'I30N',
        'I30N FB',
        'I40',
        'IONIQ',
        'IX 55',
        'IX20',
        'IX35',
        'KONA',
        'LANTRA',
        'MATRIX',
        'PONY',
        'SANTA FE',
        'SONATA',
        'TERRACAN',
        'TRAJET',
        'TUCSON',
        'TUSCON',
        'VELOSTER',
    ],
    'INFINITI': [
        'FX',
        'FX 35',
        'FX35',
        'INFINITI FX30D',
        'INFINITI Q30',
        'INFINITI Q30 S',
        'INFINITI Q50',
        'INFINITI QX30',
        'QX70',
    ],
    'ISUZU': [
        'D-MAX',
        'L35',
        'M21',
        'P 35.04',
        'TROOPER',
    ],
    'JAGUAR': [
        'E-PACE',
        'F-PACE',
        'JAGUAR',
        'JAGUAR E-PACE',
        'JAGUAR F-TYPE',
        'JAGUAR XE',
        'JAGUAR XF',
        'JAGUAR XF SPORTBRAKE',
        'JAGUAR XJ',
        'JAGUAR XK',
        'JAGUAR XKR',
        'S',
        'S TYPE',
        'S-TYPE',
        'X',
        'X TYPE',
        'X-TYPE',
        'XE',
        'XF',
        'XJ',
        'XJ 6',
        'XJ 8',
        'XJ6',
        'XJ8',
        'XJS CABRIO',
        'XK',
        'XK 8',
        'XK 8 4.0',
        'XK8',
        'XKR',
    ],
    'JEEP': [
        'CHEROKEE',
        'CJ',
        'COMMANDER',
        'COMPASS',
        'COMPASS RALLYE',
        'GRAND',
        'GRAND  CHEROKEE',
        'GRAND CHEROKEE',
        'JEEP',
        'PATRIOT',
        'RENEGADE',
        'WILLYS',
        'WRANGLER',
        'WRANGLER UNLIMITED',
    ],
    'KIA': [
        'ASIA',
        'CARENS',
        'CARNIVAL',
        "CEE'D",
        'CEED',
        'CERATO',
        'CLARUS',
        'K 2500',
        'K 2700',
        'K2500',
        'K2700',
        'K2700 II',
        'K2900 CRDI',
        'KIA',
        'MAGENTIS',
        'NIRO',
        'OPIRUS',
        'OPTIMA',
        'PICANTO',
        'PREGIO 2.7',
        'PREGIO 2.7 D',
        'PRIDE',
        'PRIDE  1.3 GLXI',
        'PROCEED',
        'RETONA',
        'RIO',
        'RIO  1.3',
        'SEPHIA',
        'SORENTO',
        'SOUL',
        'SPECTRA',
        'SPORTAGE',
        'SPORTAGE  2.0',
        'STINGER',
        'STONIC',
        'VENGA',
        'XCEED',
    ],
    'LAMBORGHINI': [
        'AVENTADOR',
        'GALLARDO',
        'HURACAN',
        'URUS',
    ],
    'LANCIA': [
        'DEDRA',
        'DELTA',
        'FULVIA',
        'K',
        'KAPPA',
        'LANCIA',
        'LYBRA',
        'MUSA',
        'PHEDRA',
        'THEMA',
        'THESIS',
        'VOYAGER',
        'Y',
        'Y 10',
        'YPSILON',
        'Z',
        'ZETA',
    ],
    'LAND ROVER': [
        'DEFENDER',
        'DEFENDER 110',
        'DEFENDER 110  SW',
        'DEFENDER 110 2.5',
        'DEFENDER 110 SW',
        'DEFENDER 110 TD5',
        'DEFENDER 130',
        'DEFENDER 130 2.4',
        'DEFENDER 130 CRC 2.5',
        'DEFENDER 130 TDS',
        'DEFENDER 90',
        'DEFENDER 90 2.5',
        'DEFENDER 90 SW',
        'DEFENDER 90 SW 2.5',
        'DISCOVERY',
        'DISCOVERY 3',
        'DISCOVERY 4',
        'DISCOVERY SPORT',
        'FREELANDER',
        'FREELANDER  1.8',
        'FREELANDER 2',
        'LAND ROVER',
        'LAND ROVER DISCOVERY 2.5 TD5',
        'LAND ROVER FREELANDER 1.8 XEI',
        'LAND ROVER FREELANDER 2.0 XEDI',
        'RANGE ROVER',
        'RANGE ROVER EVOQUE',
        'RANGE ROVER SPORT',
        'RANGE ROVER VELAR',
    ],
    'LEXUS': [
        'GS',
        'GS250',
        'GS300H',
        'GS450H',
        'IS',
        'IS 200',
        'IS 220',
        'IS 250',
        'LC500H',
        'LEXUS CT200H',
        'LEXUS ES300H',
        'LEXUS GS300',
        'LEXUS GS450H',
        'LEXUS IS200',
        'LEXUS IS220D',
        'LEXUS IS250',
        'LEXUS IS300H',
        'LEXUS NX300H',
        'LEXUS RX400H',
        'LEXUS RX450H',
        'LS500H',
        'NX300H',
        'RC300H',
        'RX',
        'RX 300',
        'RX 400 H',
        'RX450H',
        'RX450HL',
        'SC',
        'UX250H',
    ],
    'MASERATI': [
        'GHIBLI',
        'GRANTURISMO',
        'LEVANTE',
        'QUATTROPORTE',
        'SPYDER',
    ],
    'MAZDA': [
        '323 F',
        'B 2200 D',
        'B 2500',
        'B 2500 D',
        'B 2500 D 4WD PICK UP',
        'B 2500 D 4X4',
        'B 2500 TD',
        'B2500',
        'BT-50',
        'CX-3',
        'CX-30',
        'CX-5',
        'CX-7',
        'DEMIO',
        'E 2200',
        'MAZDA',
        'MAZDA  3',
        'MAZDA 2',
        'MAZDA 2 1,25I',
        'MAZDA 3',
        'MAZDA 323 F 1.4I 16V',
        'MAZDA 323 F 1.5I 16V',
        'MAZDA 323 F 1.6I 16V',
        'MAZDA 323 SEDAN 1.4I 16V',
        'MAZDA 5',
        'MAZDA 6',
        'MAZDA 626 1.8I 16V',
        'MAZDA B 2500',
        'MAZDA B2500 D 4X4',
        'MAZDA B2500 TD 4X4',
        'MAZDA CX-3',
        'MAZDA DEMIO 1.4I LP',
        'MAZDA E2200',
        'MAZDA MX-5',
        'MAZDA PREMACY',
        'MAZDA PREMACY 1,8I LP',
        'MAZDA PREMACY 1,8I SP',
        'MAZDA RX-8',
        'MAZDA TRIBUTE',
        'MAZDA3',
        'MAZDA5',
        'MAZDA6 1.8I',
        'MAZDA6 2.0 CD',
        'MAZDA6 KARAVAN 2.0 CD',
        'MAZDA6 KARAVAN 2.0 CDH',
        'MPV',
        'MX',
        'MX-30',
        'MX-5',
        'MX5',
        'PREMACY',
        'PREMACY 1,8I SP',
        'RX-8',
        'TRIBUTE',
        'XEDOS',
    ],
    'MERCEDES-BENZ': [
        '100 D',
        '190 D',
        '190 E',
        '190D',
        '200 D',
        '200 E',
        '208 D',
        '208 D SPRINTER',
        '208 D-KA',
        '230 E',
        '240 D',
        '300 CE',
        '300 D',
        '300 SL',
        '300 SL-24',
        '308 CDI',
        '308 D',
        '308 DKA',
        '310 D',
        '310 D-KA',
        '312 D',
        '314 KA',
        '409 D',
        '410 D',
        '412 D',
        '500 SL',
        '609 D',
        '611 D',
        'A',
        'A  140',
        'A  180',
        'A 140',
        'A 150',
        'A 160',
        'A 180',
        'AMG',
        'AMG C 63 S',
        'AMG CLA',
        'AMG CLS',
        'AMG GLC',
        'AMG GLE',
        'AMG GT C',
        'AMG GT S',
        'B',
        'B 180 CDI',
        'C',
        'C  200',
        'C 180',
        'C 200',
        'C 200 CDI',
        'C 220',
        'C 220 T',
        'C 230',
        'C 250',
        'C 250 D',
        'C 280',
        'CE',
        'CITAN',
        'CL',
        'CLA',
        'CLC',
        'CLK',
        'CLK 200',
        'CLK 230',
        'CLK 320',
        'CLK CABRIO',
        'CLS',
        'E',
        'E 200',
        'E 220',
        'E 230',
        'E 240',
        'E 250',
        'E 270',
        'E 280',
        'E 290',
        'E 300',
        'E 300 D',
        'E 320',
        'EQC',
        'G',
        'GL',
        'GLA',
        'GLB',
        'GLC',
        'GLE',
        'GLK',
        'GLS',
        'MARCO POLO',
        'MB 100',
        'MB 100 D',
        'MB 100 DL',
        'MERCEDES BENZ',
        'MERCEDES BENZ 312 D',
        'MERCEDES BENZ 313 CDI SPRINTER',
        'MERCEDES BENZ C',
        'MERCEDES BENZ C 180',
        'MERCEDES C 180',
        'MERCEDES SLK 230 KOMPR.',
        'MERCEDES-BENZ',
        'ML',
        'ML 270',
        'ML 270 CDI',
        'ML 320',
        'R',
        'R 320T',
        'S',
        'S 320 CDI',
        'S 350',
        'S 500',
        'SL',
        'SL 280',
        'SL 320',
        'SL 500',
        'SLC',
        'SLK',
        'SLK 200',
        'SLK 230',
        'SLK 350',
        'SPRINTER',
        'SPRINTER  313 CDI',
        'SPRINTER 208',
        'SPRINTER 208 CDI',
        'SPRINTER 208 D',
        'SPRINTER 209',
        'SPRINTER 210',
        'SPRINTER 211',
        'SPRINTER 211 CDI',
        'SPRINTER 212 D',
        'SPRINTER 213',
        'SPRINTER 213 CDI',
        'SPRINTER 308',
        'SPRINTER 308 CDI',
        'SPRINTER 308 D',
        'SPRINTER 308 D-35',
        'SPRINTER 308 D-40',
        'SPRINTER 309',
        'SPRINTER 310',
        'SPRINTER 310 D',
        'SPRINTER 311',
        'SPRINTER 311 CDI',
        'SPRINTER 312 D',
        'SPRINTER 312D',
        'SPRINTER 313',
        'SPRINTER 313 CDI',
        'SPRINTER 314',
        'SPRINTER 315',
        'SPRINTER 315 CDI',
        'SPRINTER 316',
        'SPRINTER 316 CDI',
        'SPRINTER 318',
        'SPRINTER 319',
        'SPRINTER 408 D',
        'SPRINTER 412 D',
        'SPRINTER 413',
        'SPRINTER 413 CDI',
        'SPRINTER 416',
        'SPRINTER 416 CDI',
        'SPRINTER 419',
        'SPRINTER 513',
        'SPRINTER 514',
        'SPRINTER 515',
        'SPRINTER 516',
        'SPRINTER 518',
        'SPRINTER 519',
        'V',
        'V-KLASSE',
        'VANEO',
        'VANEO 1.7',
        'VARIO 512 D',
        'VIANO',
        'VITO',
        'VITO 108',
        'VITO 108 CDI',
        'VITO 108 D',
        'VITO 109',
        'VITO 109 CDI',
        'VITO 110',
        'VITO 110 CDI',
        'VITO 110 D',
        'VITO 111',
        'VITO 111 CDI',
        'VITO 112',
        'VITO 112 CDI',
        'VITO 113',
        'VITO 114',
        'VITO 115',
        'VITO 116',
        'VITO 119',
        'VITO 120',
        'VITO 122',
        'VITO MIXTO',
        'VITO MIXTO 116',
        'VITO MIXTO 116 CDI AUT.',
        'VITO MIXTO 119 CDI AUT.',
        'VITO TOURER',
        'VITO TOURER 119 CDI AUT.',
        'X 250',
        'X 350',
    ],
    'MG': [
        'MG MGF 1.8 VVC',
        'MG ZS EV',
        'MGF',
        'TF',
        'ZR',
        'ZS EV',
        'ZT-T',
    ],
    'MINI': [
        'CLUBMAN COOPER',
        'CLUBMAN COOPER D',
        'CLUBMAN COOPER S',
        'CLUBMAN COOPER SD',
        'CLUBMAN COOPER SD ALL4',
        'CLUBMAN JOHN COOPER WORKS',
        'CLUBMAN ONE',
        'CLUBMAN ONE D',
        'COOPER',
        'COOPER CABRIO',
        'COOPER CABRIO D',
        'COOPER CABRIO S',
        'COOPER CABRIO SD',
        'COOPER CLUBMAN',
        'COOPER COUNTRYMAN',
        'COOPER COUPE',
        'COOPER D',
        'COOPER D CABRIO',
        'COOPER D CLUBMAN',
        'COOPER D COUNTRYMAN',
        'COOPER D PACEMAN',
        'COOPER PACEMAN',
        'COOPER S',
        'COOPER S CABRIO',
        'COOPER S CLUBMAN',
        'COOPER S COUNTRYMAN',
        'COOPER S COUPE',
        'COOPER S PACEMAN',
        'COOPER SD',
        'COOPER SD CABRIO',
        'COOPER SD COUNTRYMAN',
        'COOPER SD COUPE',
        'COOPER SD PACEMAN',
        'COOPER SE',
        'COUNTRYMAN COOPER',
        'COUNTRYMAN COOPER D',
        'COUNTRYMAN COOPER D ALL4',
        'COUNTRYMAN COOPER S',
        'COUNTRYMAN COOPER S ALL4',
        'COUNTRYMAN COOPER SD',
        'COUNTRYMAN COOPER SD ALL4',
        'COUNTRYMAN COOPER SE',
        'COUNTRYMAN COOPER SE ALL 4',
        'COUNTRYMAN COOPER SE ALL4',
        'COUNTRYMAN JCW ALL 4',
        'COUNTRYMAN JOHN COOPER WORKS ALL 4',
        'COUNTRYMAN ONE',
        'COUNTRYMAN ONE D',
        'JOHN COOPER WORKS',
        'JOHN COOPER WORKS CABRIO',
        'JOHN COOPER WORKS COUNTRYMAN',
        'MINI',
        'MINI COOPER',
        'MINI ONE',
        'ONE',
        'ONE CABRIO',
        'ONE CLUBMAN',
        'ONE COUNTRYMAN',
        'ONE D',
        'ONE D CLUBMAN',
        'ONE D COUNTRYMAN',
    ],
    'MITSUBISHI': [
        'ASX',
        'CABRIO',
        'CANTER',
        'CANTER 3C13',
        'CARISMA',
        'CARISMA  1.6',
        'COLT',
        'ECLIPSE',
        'ECLIPSE CROSS',
        'GALANT',
        'GRANDIS',
        'I-MIEV',
        'L 200',
        'L 200 2.5',
        'L 200 2.5 TD',
        'L 200 2.5 TDGLX',
        'L 200 2.5 TDI',
        'L 300',
        'L-200',
        'L-200 2.5',
        'L200',
        'L200 2.5',
        'LANCER',
        'LANCER EVOLUTION',
        'LANCER EVOLUTION IX',
        'LANCER EVOLUTION X',
        'MITSUBISHI',
        'MITSUBISHI DA(0) CARISMA',
        'OUTLANDER',
        'PAJERO',
        'PAJERO PININ',
        'PAJERO SPORT',
        'SPACE RUNNER',
        'SPACE STAR',
        'SPACE WAGON',
        'SPACESTAR',
    ],
    'NISSAN': [
        '200 SX',
        '350 Z',
        '350Z',
        '370Z',
        'ALMERA',
        'ALMERA TINO',
        'ATLEON',
        'ATLEON 120',
        'ATLEON 35.13',
        'CABSTAR',
        'CABSTAR 110 E',
        'CABSTAR 120 E',
        'CABSTAR 35.11',
        'CABSTAR 35.12',
        'CABSTAR 35.13',
        'CABSTAR 35.15',
        'CABSTAR E 120',
        'CABSTAR E TL 110',
        'CABSTAR E TL 110.35',
        'CABSTAR TL 35',
        'CUBE',
        'D 22',
        'E-NV200',
        'GT-R',
        'JUKE',
        'L 35-085',
        'L35.09',
        'L56.35',
        'LEAF',
        'MAXIMA',
        'MICRA',
        'MICRA  1.0',
        'MURANO',
        'NAVARA',
        'NAVARA 2.3',
        'NAVARA 2.5',
        'NAVARA 2.5 DI',
        'NAVARA 3.0',
        'NISSAN',
        'NISSAN NT400',
        'NISSAN NT400 CABSTAR',
        'NOTE',
        'NP300 NAVARA 2.3',
        'NT 400',
        'NT400',
        'NT400 CABSTAR',
        'NT400 CABSTAR 35.12',
        'NT400 CABSTAR 35.13',
        'NV 400',
        'NV200',
        'NV200 FURGON 1.5',
        'NV300',
        'NV400',
        'PATHFINDER',
        'PATROL',
        'PATROL GR',
        'PICK UP',
        'PICK UP 2.5',
        'PRIMA STAR',
        'PRIMASTAR',
        'PRIMERA',
        'PRIMERA  1.6',
        'PRIMERA  1.8',
        'PULSAR',
        'QASHQAI',
        'QASHQAI+2',
        'SERENA',
        'SKYLINE',
        'SUNNY',
        'TERRANO',
        'TERRANO II',
        'TERRANO II 2.7 TD',
        'TIIDA',
        'TRADE 100',
        'TRADE 2.8 D',
        'TRADE 3.0 D',
        'VANETTE',
        'X-TRAIL',
    ],
    'OPEL': [
        'ADAM',
        'ADAM CUP',
        'AGILA',
        'AMPERA',
        'ANTARA',
        'ASTRA',
        'ASTRA  1.2',
        'ASTRA  1.4',
        'ASTRA  1.6',
        'ASTRA  1.7',
        'ASTRA 1.4',
        'ASTRA 1.6',
        'ASTRA GTC',
        'ASTRA VAN',
        'ASTRA VAN 1.7',
        'ASTRA+',
        'CALIBRA',
        'CAMPO 2.5',
        'CAMPO 4X4',
        'CASCADA',
        'COMBO',
        'COMBO 1.4',
        'COMBO 1.6',
        'COMBO 1.7',
        'COMBO CARGO',
        'COMBO CARGO 1.3',
        'COMBO CARGO 1.4',
        'COMBO CARGO 1.6',
        'COMBO LIFE',
        'COMBO VAN',
        'COMBO VAN 1.3',
        'COMBO VAN 1.4',
        'COMBO VAN 1.6',
        'COMBO VAN 1.7',
        'COMBO-C',
        'COMBO-C 1.7',
        'COMBO-D-VAN',
        'CORSA',
        'CORSA  1.0',
        'CORSA  1.2',
        'CORSA  1.4',
        'CORSA 1.0',
        'CORSA 1.2',
        'CORSA 1.2 16V',
        'CORSA COMBO 1.7 D',
        'CORSA VAN',
        'CORSA VAN 1.3',
        'CORSA-E',
        'CROSSLAND X',
        'FRONTERA',
        'GRANDLAND X',
        'GT',
        'INSIGNIA',
        'INSIGNIA COUNTRY TOURER',
        'INSIGNIA GRAND SPORT',
        'INSIGNIA SPORTS TOURER',
        'KADETT',
        'KARL',
        'MANTA',
        'MERIVA',
        'MOKKA',
        'MONTEREY',
        'MOVANO',
        'MOVANO 2.3',
        'MOVANO 2.5',
        'OLYMPIA',
        'OMEGA',
        'OPEL',
        'OPEL ASTRA',
        'OPEL ASTRA 1,4',
        'OPEL ASTRA 1,6',
        'OPEL ASTRA 1.4 16V',
        'OPEL ASTRA 1.6',
        'OPEL ASTRA 1.6 16V',
        'OPEL CORSA',
        'OPEL CORSA 1,0',
        'OPEL CORSA 1.0 12V',
        'OPEL CORSA 1.2 16V',
        'OPEL VECTRA 1,6',
        'OPEL VECTRA 2.0',
        'SIGNUM',
        'SINTRA',
        'SPEEDSTER',
        'TIGRA',
        'VECTRA',
        'VIVARO',
        'VIVARO 1,6 CDTI',
        'VIVARO 1.6 CDTI',
        'VIVARO 1.9',
        'VIVARO 2.0',
        'VIVARO 2.0 CDTI',
        'VIVARO 2.0 DT',
        'VIVARO 2.5',
        'VIVARO COMBI 1.9',
        'VIVARO COMBI 2.5',
        'VIVARO VAN',
        'VIVARO-B',
        'ZAFIRA',
        'ZAFIRA LIFE',
        'ZAFIRA TOURER',
    ],
    'PEUGEOT': [
        '106  1.1 I',
        '206  1.4  HDI',
        '206  1.4  I',
        '206  1.4 I',
        '206  CABRIOLET 1.6',
        '206 1.4 HDI',
        '206 1.4 I',
        '206 FURGON 1.4',
        '206+',
        '207 FURGON 1.4',
        '307 1.6 I',
        '4008 4X4',
        'BIPPER',
        'BIPPER 1.3',
        'BIPPER 1.4',
        'BOXER',
        'BOXER 2.0',
        'BOXER 2.2',
        'BOXER 2.4',
        'BOXER 2.4 TD',
        'BOXER 2.5',
        'BOXER 2.5 D',
        'BOXER 2.5 TD',
        'BOXER 2.8',
        'BOXER 3.0',
        'BOXER 350 L',
        'BOXER 350 LHD',
        'BOXER 350 LHTD',
        'BOXPT 3000L1 100HDI',
        'BOXPTDK3500L3V 120HDI',
        'EXPERT',
        'EXPERT 1.6',
        'EXPERT 1.9',
        'EXPERT 2.0',
        'EXPERT TRAVELLER',
        'ION',
        'J 5',
        'PARTNER',
        'PARTNER 1.4 I',
        'PARTNER 1.6',
        'PARTNER 170 C',
        'PARTNER 170 C 1.6',
        'PARTNER 170C 1.4',
        'PARTNER 170C 1.6',
        'PARTNER 170C 2.0',
        'PARTNER 190C 1.4',
        'PARTNER 190C 1.6',
        'PARTNER 190C 1.9',
        'PARTNER 190C 2.0',
        'PARTNER 2.0',
        'PARTNER MULTISPA.2.0',
        'PEUGEOT',
        'PEUGEOT  206  1.6  I',
        'PEUGEOT 106',
        'PEUGEOT 306',
        'PEUGEOT 406',
        'PEUGEOT BOXER',
        'PEUGEOT BOXER 2,8 HDI',
        'RANCH',
        'RCZ',
        'RIFTER',
    ],
    'PORSCHE': [
        '718 CAYMAN GT4',
        '911 CARRERA',
        '911 CARRERA 2',
        '911 CARRERA 4',
        '911 CARRERA 4 GTS',
        '911 CARRERA 4S',
        '911 CARRERA GTS',
        '911 CARRERA S',
        '911 GT2 RS',
        '911 GT3',
        '911 GT3 RS',
        '911 TARGA 4',
        '911 TARGA 4 GTS',
        '911 TARGA 4S',
        '911 TURBO',
        '911 TURBO S',
        '928 S',
        'BOXSTER',
        'BOXSTER GTS',
        'BOXSTER S',
        'BOXSTER T',
        'CAYENNE',
        'CAYENNE DIESEL',
        'CAYENNE E-HYBRID',
        'CAYENNE GTS',
        'CAYENNE S',
        'CAYENNE S DIESEL',
        'CAYENNE S E-HYBRID',
        'CAYENNE TURBO',
        'CAYENNE TURBO S E-HYBRID',
        'CAYMAN',
        'CAYMAN S',
        'MACAN',
        'MACAN GTS',
        'MACAN S',
        'MACAN S DIESEL',
        'MACAN TURBO',
        'PANAMERA',
        'PANAMERA 4',
        'PANAMERA 4 E-HYBRID',
        'PANAMERA 4S',
        'PANAMERA 4S DIESEL',
        'PANAMERA DIESEL',
        'PANAMERA GTS',
        'PANAMERA S E-HYBRID',
        'PANAMERA TURBO',
        'PANAMERA TURBO S E-HYBRID',
        'TAYCAN 4S',
        'TAYCAN TURBO',
        'TAYCAN TURBO S',
    ],
    'RENAULT': [
        '52 AFA 1',
        'ALASKAN 2.3 DCI',
        'AVANTIME',
        'B 110.35',
        'B 110.35 C',
        'CAPTUR',
        'CLIO',
        'CLIO  1,5  DCI',
        'CLIO  1.2',
        'CLIO  1.2 BEBOP',
        'CLIO  1.2 FIDJI',
        'CLIO  1.2 RL',
        'CLIO  1.2 RN',
        'CLIO  1.4',
        'CLIO  1.5',
        'CLIO 1,5 DCI',
        'CLIO 1.2',
        'CLIO 1.2 16V',
        'CLIO 1.2 RL',
        'CLIO 1.2 SERVISER',
        'CLIO 1.4',
        'CLIO 1.5',
        'CLIO 1.5 DCI',
        'CLIO 1.5 SERVISER',
        'CLIO GRANDTOUR',
        'CLIO RT 1,2 3V',
        'CLIO RTA 1,2  5V',
        'CLIO SERVISER 1.2',
        'CLIO SERVISER 1.5',
        'CLIO VAN',
        'CLIO VAN 1.5',
        'ESPACE',
        'EXPRESS',
        'EXPRESS FURGON 1.9',
        'FLUENCE',
        'FLUENCE Z.E',
        'FN 40 B7',
        'GRAND SCENIC',
        'GRAND SCENIC HYBRID ASSIST',
        'KADJAR',
        'KANGOO',
        'KANGOO  1.2',
        'KANGOO  1.4',
        'KANGOO  1.9',
        'KANGOO 1.2',
        'KANGOO 1.4',
        'KANGOO 1.5',
        'KANGOO 1.6',
        'KANGOO 1.9',
        'KANGOO EXPRESS',
        'KANGOO EXPRESS  1.9',
        'KANGOO EXPRESS 1.2',
        'KANGOO EXPRESS 1.4',
        'KANGOO EXPRESS 1.5',
        'KANGOO EXPRESS 1.6',
        'KANGOO EXPRESS 1.9',
        'KANGOO EXPRESS Z.E',
        'KANGOO EXPRESS Z.E.',
        'KOLEOS',
        'LAGUNA',
        'LAGUNA  1.8',
        'LATITUDE',
        'MASCOTT',
        'MASCOTT 110.35',
        'MASCOTT 110.50',
        'MASCOTT 120.35',
        'MASCOTT 130.35',
        'MASCOTT 130.35 DC',
        'MASCOTT 150.35',
        'MASTER',
        'MASTER  FURGON  2,8',
        'MASTER  FURGON  2.8',
        'MASTER 2,5 DCI',
        'MASTER 2.2',
        'MASTER 2.3',
        'MASTER 2.3 DCI',
        'MASTER 2.5',
        'MASTER 2.5 D',
        'MASTER 2.5 DCI',
        'MASTER 2.8',
        'MASTER 2.8 DTI',
        'MASTER 3.0',
        'MASTER 3T5 145',
        'MASTER 3T5 165',
        'MASTER COMBI 2.5',
        'MASTER FURGON',
        'MASTER FURGON 1.9',
        'MASTER FURGON 2,2',
        'MASTER FURGON 2,5',
        'MASTER FURGON 2.2',
        'MASTER FURGON 2.3',
        'MASTER FURGON 2.5',
        'MASTER FURGON 2.5 DCI',
        'MASTER FURGON 2.8',
        'MASTER FURGON 2.8 DT',
        'MASTER FURGON 3.0',
        'MASTER KASON 2.2',
        'MASTER KASON 2.5',
        'MASTER KASON 2.8',
        'MASTER T 35 D',
        'MASTER VG H6E 3',
        'MAXITY',
        'MAXITY 120.35',
        'MAXITY 130.35',
        'MAXITY 140.35',
        'MAXITY 150.35',
        'MEGANE',
        'MEGANE  1.4',
        'MEGANE  1.6',
        'MEGANE  1.6 E ALIZE',
        'MEGANE  1.9',
        'MEGANE  COUPE 1.6',
        'MEGANE  SCENIC 1.6',
        'MEGANE  SCENIC 1.9',
        'MEGANE 1,9 DCI',
        'MEGANE 1.4',
        'MEGANE 1.5',
        'MEGANE 1.6',
        'MEGANE COUPE',
        'MEGANE COUPE 1.6',
        'MEGANE E-TECH PLUG-IN HYBRID',
        'MEGANE GRANDTOUR',
        'MEGANE SCENIC',
        'MEGANE SCENIC 1.6',
        'MEGANE SCENIC 1.6 16V',
        'MODUS',
        'R19',
        'R19  1.4 RT',
        'R4',
        'R4 GTL',
        'R5',
        'R5  CAMPUS',
        'R5  FIVE',
        'R5 CAMPUS',
        'R5 SERVISER',
        'RENAULT',
        'RENAULT  MEGANE',
        'RENAULT  TWINGO',
        'RENAULT BA (MEGANE)',
        'RENAULT CLIO',
        'RENAULT CLIO 1,4',
        'RENAULT CLIO RT 1,2 3V',
        'RENAULT CLIO RTA 1,2  5V',
        'RENAULT LAGUNA 1,6',
        'RENAULT LAGUNA 1,9 DCI',
        'RENAULT MASTER 2,5 DCI',
        'RENAULT MEGANE (BA)',
        'RENAULT MEGANE (BA,DA)',
        'RENAULT MEGANE 1,4',
        'RENAULT MEGANE 1,6',
        'RENAULT MEGANE 1,9 DCI',
        'RENAULT MEGANE CLASSIC',
        'RENAULT MEGANE RN 1,6 E',
        'RENAULT MEGANE SCENIC',
        'RENAULT MEGANE SCENIC 1,6',
        'RENAULT MEGANE SCENIC 1,9 DCI',
        'RENAULT MEGANE SCENIC 1.6',
        'RENAULT RENAULT',
        'RENAULT RENAULT CLIO',
        'RENAULT TWINGO (C06)',
        'RENAULT TWINGO 1,2',
        'RENAULT TWINGO BASE',
        'SAFRANE',
        'SCENIC',
        'SCENIC HYBRID ASSIST',
        'TALISMAN',
        'TALISMAN GRANDTOUR',
        'THALIA',
        'THALIA  1.4',
        'THALIA 1.4',
        'TRAFIC',
        'TRAFIC 1.6',
        'TRAFIC 1.9',
        'TRAFIC 2.0',
        'TRAFIC 2.2 4X4',
        'TRAFIC 2.5',
        'TRAFIC 2.5 D 4X4',
        'TRAFIC COMBI 1.9',
        'TRAFIC FURGON 2.0',
        'TRAFIC FURGON 2.5',
        'TRAFIC T 1100 D',
        'TRAFIC T 1400 D',
        'TRAFIC T 31 F',
        'TRAFIC T 313',
        'TRAFIC TB 2 G',
        'TWINGO',
        'TWINGO  1.2',
        'TWINGO 1.2',
        'VEL SATIS',
        'VELSATIS',
        'WIND',
        'ZOE',
        'ZOE Z.E.',
    ],
    'ROVER': [
        '214  I',
        '214  SI',
        '216 SI',
        'LAND-ROVER',
        'MINI',
        'ROVER',
        'ROVER 214 SI',
        'ROVER RF (200)',
        'STREETWISE',
    ],
    'SEAT': [
        'ALHAMBRA',
        'ALTEA',
        'ALTEA 4 FREETRACK',
        'ALTEA 4 XL',
        'ALTEA FREETRACK',
        'ALTEA XL',
        'ARONA',
        'AROSA',
        'AROSA  1.0',
        'ATECA',
        'CORDOBA',
        'CORDOBA  1.4',
        'CORDOBA  1.6',
        'CUPRA ATECA',
        'EXEO',
        'EXEO ST',
        'IBIZA',
        'IBIZA  1.4',
        'IBIZA  1.9',
        'IBIZA  1.9  TDI',
        'IBIZA 1.4',
        'IBIZA ST',
        'IBIZA VAN',
        'INCA',
        'INCA 1.4',
        'INCA 1.9',
        'INCA 1.9 DCL',
        'LEON',
        'LEON  1.6',
        'LEON  1.9',
        'LEON 1.6',
        'LEON 1.9 TDI',
        'LEON SC',
        'LEON SPORTOURER ST',
        'LEON SPORTSTOURER',
        'LEON ST',
        'LEON X-PERIENCE',
        'MII',
        'SEAT',
        'SEAT SEAT CORDOBA 1.4 SE JUBILEE 44 KW',
        'TARRACO',
        'TOLEDO',
        'TOLEDO  1.9',
        'TOLEDO 1.9',
    ],
    'SKODA': [
        'CITIGO',
        'E-CITIGO',
        'FABIA',
        'FABIA  1.4',
        'FABIA 1.4',
        'FABIA 1.6',
        'FABIA COMBI',
        'FAVORIT',
        'FELICIA',
        'FELICIA  1.6',
        'FELICIA  LXI',
        'FELICIA PICK UP',
        'FELICIA PICK UP 1.3',
        'FELICIA PICK UP 1.9D',
        'FELICIA PICK UP LXI',
        'FORMAN',
        'KAMIQ',
        'KAROQ',
        'KODA',
        'KODA FELICIA',
        'KODA OCTAVIA',
        'KODA OCTAVIA 1,9 TDI',
        'KODIAQ',
        'OCTAVIA',
        'OCTAVIA  1.9',
        'OCTAVIA  COMBI 1.9',
        'OCTAVIA 1.9 TDI',
        'OCTAVIA COMBI',
        'OCTAVIA COMBI 1.6',
        'OCTAVIA COMBI 1.9 TDI',
        'OCTAVIA COMBI 2.0',
        'OCTAVIA RS',
        'PICK UP LX',
        'PRAKTIK 1.2',
        'PRAKTIK 1.4',
        'PRAKTIK 1.6',
        'RAPID',
        'RAPID 1.2',
        'RAPID 1.4',
        'RAPID 1.6',
        'ROOMSTER',
        'ROOMSTER 1.2',
        'SCALA',
        'SUPERB',
        'SUPERB COMBI',
        'YETI',
    ],
    'SMART': [
        'CABRIO',
        'COUPE',
        'COUPE 30',
        'ELECTRIC DRIVE',
        'EQ FORFOUR',
        'EQ FORTWO',
        'FORFOUR',
        'FORTWO',
        'ROADSTER',
        'SMART',
        'SMART FORFOUR',
        'SMART FORTWO',
        'SMART FORTWO COUPE',
    ],
    'SSANGYONG': [
        'ACTYON',
        'ACTYON SPORTS 2.0',
        'KORANDO',
        'KYRON',
        'MUSSO',
        'REXTON',
        'RODIUS',
        'TIVOLI',
        'XLV',
    ],
    'SUBARU': [
        'B9 TRIBECA',
        'FORESTER',
        'FORESTER HEV',
        'IMPREZA',
        'J 10',
        'J 12',
        'J 13',
        'JUSTY',
        'JUSTY G3X',
        'LEGACY',
        'LEONE',
        'LEVORG',
        'OUTBACK',
        'SUBARU',
        'SUBARU BRZ',
        'SUBARU TREZIA',
        'SUBARU XV',
        'TRIBECA',
        'TRIBECA WAGON 3.6',
        'VIVIO',
        'WRX',
        'XV',
    ],
    'SUZUKI': [
        'ALTO',
        'BALENO',
        'CARRY',
        'CARRY VAN SUPER',
        'CELERIO',
        'GRAND',
        'GRAND VITARA',
        'GRAND VITARA  1.6',
        'GRAND VITARA 1.6',
        'GRAND VITARA 2.0 TD',
        'GRAND VITARA XL-7',
        'IGNIS',
        'JIMMY',
        'JIMNY',
        'JIMNY  1.3',
        'JIMNY 1.3',
        'JIMNY 1.3 4WD',
        'KIZASHI',
        'LIANA',
        'SAMURAI',
        'SAMURAI  1.3',
        'SAMURAI LX',
        'SAMURAI SJ700',
        'SAMURAI VX',
        'SANTANA',
        'SIDEKICK',
        'SJ 410',
        'SJ 413',
        'SPLASH',
        'SUZUKI',
        'SUZUKI SAMURAI 1.3',
        'SUZUKI SAMURAI VX',
        'SUZUKI VITARA LX',
        'SUZUKI VITARA VX 5D',
        'SWIFT',
        'SX4',
        'VITARA',
        'VITARA 1.6 16V',
        'VITARA ET',
        'WAGON',
        'WAGON R',
        'WAGON-R',
    ],
    'TESLA': [
        'MODEL 3',
        'MODEL S',
        'MODEL X',
    ],
    'TOYOTA': [
        '4 RUNNER',
        'AURIS',
        'AVENSIS',
        'AVENSIS VERSO',
        'AYGO',
        'C-HR',
        'CAMRY',
        'CARINA',
        'CELICA',
        'COROLLA',
        'COROLLA  1.4',
        'COROLLA  1.6',
        'COROLLA 1.4',
        'COROLLA VERSO',
        'DYNA 100',
        'DYNA 150',
        'HI ACE 2.4',
        'HI LUX',
        'HI LUX 2.4 D',
        'HI LUX 2.5',
        'HIACE',
        'HIGHLANDER',
        'HILUX',
        'HILUX 2.4',
        'HILUX 2.4 D',
        'HILUX 2.5',
        'HILUX 3.0',
        'IQ',
        'LAND',
        'LAND CRUISER',
        'LAND CRUISER 100',
        'LAND CRUISER 120',
        'LAND CRUISER 90',
        'LAND CRUISER 95',
        'LAND CRUISER V8',
        'LANDCRUISER',
        'LANDCRUISER 120',
        'LANDCRUISER 95',
        'LEXUS',
        'MR 2',
        'MR2',
        'PASEO',
        'PICNIC',
        'PREVIA',
        'PRIUS',
        'PRIUS PLUS',
        'PROACE',
        'PROACE CITY',
        'PROACE CITY VERSO',
        'RAV  4',
        'RAV 4',
        'RAV 4 2.0',
        'RAV 4 2.0 D-4D',
        'RAV4',
        'RUNNER 4',
        'STARLET',
        'SUPRA',
        'TOYOTA',
        'TOYOTA Z',
        'URBAN CRUISER',
        'VERSO',
        'VERSO-S',
        'YARIS',
        'YARIS  1.0',
        'YARIS  1.3',
        'YARIS 1.3',
        'YARIS 1.4',
        'YARIS VAN 1.0',
        'YARIS VERSO',
    ],
    'VOLKSWAGEN': [
        '1200 J',
        '2 DXOFE',
        '2DXOFE',
        '7 DB',
        '70 X 1C',
        '70 X OA',
        '70 X OB',
        '70 X OC',
        '70 X1A',
        '70 X1C',
        '70 XOA',
        '70 XOD',
        'AMAROK',
        'AMAROK 2.0',
        'AMAROK 3.0',
        'ARTEON',
        'BEETLE',
        'BEETLE CABRIOLET',
        'BORA',
        'BORA  1.9',
        'BUGGY',
        'CADDY',
        'CADDY 1.0',
        'CADDY 1.2',
        'CADDY 1.4',
        'CADDY 1.6',
        'CADDY 1.9',
        'CADDY 1.9 D',
        'CADDY 1.9 SDI',
        'CADDY 1.9 TDI',
        'CADDY 2.0',
        'CADDY D',
        'CADDY LIFE',
        'CADDY LIFE 1.9',
        'CADDY MAXI',
        'CADDY MAXI 1.0',
        'CADDY MAXI 1.2',
        'CADDY MAXI 1.4',
        'CADDY MAXI 1.6',
        'CADDY MAXI 1.9',
        'CADDY MAXI 2.0',
        'CADDY MAXI KOMBI',
        'CADDY MAXI LIFE',
        'CADDY VAN',
        'CADDY VAN 1.9',
        'CALIFORNIA',
        'CALIFORNIA BEACH',
        'CARAVELLA',
        'CARAVELLE',
        'CC',
        'CORRADO',
        'CRAFTER',
        'CRAFTER 2.0',
        'CRAFTER 2.0 TDI',
        'CRAFTER 2.5',
        'CRAFTER 30',
        'CRAFTER 30 2.0',
        'CRAFTER 30 2.5',
        'CRAFTER 35',
        'CRAFTER 35  2.5',
        'CRAFTER 35 2.0',
        'CRAFTER 35 2.5',
        'CRAFTER 50 2.0',
        'CRAFTER 50 2.5',
        'DOKA',
        'DOKA-PRITSCHE',
        'DOKA-PRITSCHE TDI',
        'E-GOLF',
        'EOS',
        'EUP!',
        'FOX',
        'GOLF',
        'GOLF  1.4',
        'GOLF  1.4 CL',
        'GOLF  1.6',
        'GOLF  1.9',
        'GOLF  1.9  TDI',
        'GOLF  1.9 SDI',
        'GOLF  1.9 TDI',
        'GOLF  JX',
        'GOLF  JXD',
        'GOLF 1,9 TDI',
        'GOLF 1.4',
        'GOLF 1.6',
        'GOLF 1.9',
        'GOLF 1.9 SDI',
        'GOLF 1.9 TDI',
        'GOLF 1.9 TDI 4M',
        'GOLF CABRIO',
        'GOLF CABRIOLET',
        'GOLF CL',
        'GOLF GTE',
        'GOLF GTI',
        'GOLF JXD',
        'GOLF PLUS',
        'GOLF RABBIT',
        'GOLF VARIANT',
        'ID.3 PRO',
        'JETTA',
        'KARMANN GHIA',
        'KOMBI',
        'LT',
        'LT 28',
        'LT 28 2.4',
        'LT 28 D',
        'LT 35',
        'LT 35 2,5',
        'LT 35 2.5',
        'LT 35 2.5 TDI',
        'LT 35 2.8',
        'LT 35 2.8 TDI',
        'LT 35 Z',
        'LT 46 2.5 TDI',
        'LT 46 2.8',
        'LT35',
        'LT35 2.5',
        'LUPO',
        'LUPO  1.0',
        'LUPO  1.4',
        'MULTIVAN',
        'MULTIVAN 2.5',
        'MULTIVAN STARTLINE',
        'NEEW BEETLE',
        'NEW BEETLE',
        'NEWBEETLE',
        'PASSAT',
        'PASSAT  1.8 T',
        'PASSAT  1.9',
        'PASSAT  1.9  TDI',
        'PASSAT  1.9 TDI',
        'PASSAT  VARIANT 1.9',
        'PASSAT 1,9 TDI',
        'PASSAT 1.9',
        'PASSAT 1.9 TDI',
        'PASSAT CC',
        'PHAETON',
        'POLO',
        'POLO  1.0',
        'POLO  1.2',
        'POLO  1.4',
        'POLO  1.9',
        'POLO  60',
        'POLO 1.2',
        'POLO 1.4',
        'SCIROCCO',
        'SHARAN',
        'SHUTTLE',
        'SPEEDER T5',
        'SPEEDER T6',
        'T-CROSS',
        'T-ROC',
        'T2',
        'T4',
        'TIGUAN',
        'TOUAREG',
        'TOURAN',
        'TRANSPORTER',
        'TRANSPORTER  2.5',
        'TRANSPORTER 1,9',
        'TRANSPORTER 1.9',
        'TRANSPORTER 1.9 D',
        'TRANSPORTER 1.9 TD',
        'TRANSPORTER 1.9 TDI',
        'TRANSPORTER 2,4 D',
        'TRANSPORTER 2,5 TDI',
        'TRANSPORTER 2.0',
        'TRANSPORTER 2.0 TDI',
        'TRANSPORTER 2.4',
        'TRANSPORTER 2.4 D',
        'TRANSPORTER 2.5',
        'TRANSPORTER 2.5 TDI',
        'TRANSPORTER 3.2',
        'TRANSPORTER 70 X0D',
        'TRANSPORTER 70 XOA',
        'TRANSPORTER D',
        'TRANSPORTER K+',
        'TRANSPORTER K+ 1.9',
        'TRANSPORTER K+ 2.0',
        'TRANSPORTER K+ 2.5',
        'TRANSPORTER SYNCRO',
        'TRANSPORTER T5',
        'UP!',
        'UP! 1.0',
        'VENTO',
        'VOLKSWAGEN',
        'VOLKSWAGEN GOLF 1,9 TD',
        'VOLKSWAGEN GOLF 1,9 TDI',
        'VOLKSWAGEN GOLF 1.9 TDI',
        'VOLKSWAGEN PASSAT 1,9 TDI',
        'VOLKSWAGEN PASSAT 1.9 TDI',
        'VOLKSWAGEN TRANSPORTER 2,5 TDI',
        'VW VW  POLO 1,0L 37KW',
        'VW VW  POLO 1,4L 44KW',
        'VW VW  POLO CLASSIC 1,4L 44KW',
        'VW VW GOLF CL 1,4L 44KW',
        'VW VW GOLF CL D 1,9L 47KW',
        'VW VW PASSAT LIM. 1.8T 110KW',
        'VW VW PASSAT LIM.1.9 TDI 81KW',
    ],
    'VOLVO': [
        'C',
        'C 70',
        'C30',
        'C40 CROSS COUNTRY',
        'C70',
        'S',
        'S 40',
        'S 40  1.8',
        'S 60',
        'S 60  2.4',
        'S 60 CROSS COUNTRY',
        'S 70',
        'S 80',
        'S 90',
        'S 90 T8 TWIN ENGINE',
        'S40',
        'S60',
        'S60 CROSS COUNTRY',
        'S70',
        'S80',
        'S90',
        'S90 T8 TWIN ENGINE',
        'V',
        'V 40',
        'V 40  1.9',
        'V 40 CROSS COUNTRY',
        'V 50',
        'V 60',
        'V 60 CROSS COUNTRY',
        'V 70',
        'V 70  2.4',
        'V 90',
        'V 90 CROSS COUNTRY',
        'V 90 T8 TWIN ENGINE',
        'V40',
        'V40 CROSS COUNTRY',
        'V50',
        'V60',
        'V60 CROSS COUNTRY',
        'V70',
        'V90',
        'V90 CROSS COUNTRY',
        'V90 T8 TWIN ENGINE',
        'VOLVO',
        'VOLVO S40',
        'VOLVO S40 1.6',
        'VOLVO V 40 1,9 DTI',
        'XC',
        'XC 40',
        'XC 60',
        'XC 60 T8 TWIN ENGINE',
        'XC 70',
        'XC 90',
        'XC 90 T8 TWIN ENGINE',
        'XC40',
        'XC60',
        'XC60 T8 TWIN ENGINE',
        'XC70',
        'XC90',
        'XC90 T8 TWIN ENGINE',
    ],
}

# ---------------------------------------------------------------------------
# Alias → canonical key  (handles encoding variants, abbreviations)
# ---------------------------------------------------------------------------

_ALIAS_MAP: dict[str, str] = {
    'VW': 'VOLKSWAGEN',
    'VOLKSWAGEN': 'VOLKSWAGEN',
    'SKODA': 'SKODA',
    'ŠKODA': 'SKODA',
    'KODA': 'SKODA',
    'MERCEDES-BENZ': 'MERCEDES-BENZ',
    'MERCEDES BENZ': 'MERCEDES-BENZ',
    'MERCEDES': 'MERCEDES-BENZ',
    'MERCEDESBENZ': 'MERCEDES-BENZ',
    'BMW': 'BMW',
    'MINI': 'MINI',
    'AUDI': 'AUDI',
    'SEAT': 'SEAT',
    'CITROEN': 'CITROEN',
    'CITROËN': 'CITROEN',
    'CITROEN': 'CITROEN',
    'PEUGEOT': 'PEUGEOT',
    'RENAULT': 'RENAULT',
    'OPEL': 'OPEL',
    'FORD': 'FORD',
    'FORD EUROPE': 'FORD',
    'FIAT': 'FIAT',
    'TOYOTA': 'TOYOTA',
    'HYUNDAI': 'HYUNDAI',
    'KIA': 'KIA',
    'HONDA': 'HONDA',
    'NISSAN': 'NISSAN',
    'MAZDA': 'MAZDA',
    'SUZUKI': 'SUZUKI',
    'VOLVO': 'VOLVO',
    'DACIA': 'DACIA',
    'CHEVROLET': 'CHEVROLET',
    'CHEVY': 'CHEVROLET',
    'MITSUBISHI': 'MITSUBISHI',
    'ALFA ROMEO': 'ALFA ROMEO',
    'ALFA': 'ALFA ROMEO',
    'LAND ROVER': 'LAND ROVER',
    'LAND-ROVER': 'LAND ROVER',
    'JEEP': 'JEEP',
    'SUBARU': 'SUBARU',
    'PORSCHE': 'PORSCHE',
    'JAGUAR': 'JAGUAR',
    'LEXUS': 'LEXUS',
    'INFINITI': 'INFINITI',
    'CHRYSLER': 'CHRYSLER',
    'DODGE': 'DODGE',
    'SMART': 'SMART',
    'LANCIA': 'LANCIA',
    'SAAB': 'SAAB',
    'DS': 'DS',
    'DS AUTOMOBILES': 'DS',
    'DAEWOO': 'DAEWOO',
    'SSANGYONG': 'SSANGYONG',
    'SSANG YONG': 'SSANGYONG',
    'TESLA': 'TESLA',
    'MASERATI': 'MASERATI',
    'BENTLEY': 'BENTLEY',
    'ROLLS-ROYCE': 'ROLLS-ROYCE',
    'ROLLS ROYCE': 'ROLLS-ROYCE',
    'ISUZU': 'ISUZU',
    'ROVER': 'ROVER',
    'MG': 'MG',
}


def lookup_models(make: str | None, year: int | None = None) -> list[str]:
    """
    Return a sorted list of known model names for *make*.

    Parameters
    ----------
    make  : Manufacturer string as returned by vininfo (any case).
    year  : Currently unused; reserved for future year-range filtering.

    Returns
    -------
    List of model strings, empty list if brand unknown.
    """
    if not make:
        return []
    key = make.strip().upper()
    # Direct hit
    if key in BRAND_MODELS:
        return BRAND_MODELS[key]
    # Alias hit
    canonical = _ALIAS_MAP.get(key)
    if canonical and canonical in BRAND_MODELS:
        return BRAND_MODELS[canonical]
    # Prefix / substring hit (e.g. "VW Group" → "VOLKSWAGEN")
    for alias, canonical in _ALIAS_MAP.items():
        if key.startswith(alias) or alias.startswith(key):
            if canonical in BRAND_MODELS:
                return BRAND_MODELS[canonical]
    return []


def all_brands() -> list[str]:
    """Return a sorted list of all known canonical brand names."""
    return sorted(BRAND_MODELS.keys())
